import './globals.css';
import { Inter } from 'next/font/google';
import { EventsProvider } from './eventsFetcher'; // Adjust the import path as needed

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <EventsProvider>
          {children}
        </EventsProvider>
      </body>
    </html>
  );
}